controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Areas;
use app\models\Events;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' =>  Events::find()->orderBy("date ASC")->where("date >= :date", [":date" => date("Y-m-d")]),
            'pagination' => [
                'pageSize' => 9,
            ],

        ]);
        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    public function actionViewArea($id)
    {
        if (($model = Areas::findOne($id)) !== null) {
            $dataProvider = new ActiveDataProvider([
                'query' =>  Events::find()->orderBy("date ASC")->where("date >= :date", [":date" => date("Y-m-d")])->andWhere("area_id = :aid", [":aid" => $id]),
                'pagination' => [
                    'pageSize' => 6,
                ],
            ]);
            return $this->render("view-area", [
                "model" =>  $model,
                "dataProvider"  =>  $dataProvider,
            ]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAreas()
    {
        $dataProvider = new ActiveDataProvider([
            "query" =>  Areas::find(),
            'pagination' => [
                'pageSize' => 3,
            ],
        ]);
        return $this->render("areas", ["dataProvider" => $dataProvider]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


}

views/site/_item-area.php
<?php
/**
 * @var $model app\models\Areas
 */
use yii\helpers\Html;
use yii\helpers\Url;
use app\helpers\ImageHelper;
?>
<div class="col-sm-6 col-md-3 list-item">
    <div class="thumbnail">
        <?=Html::img(
            !empty($model->photo) ? ImageHelper::getThumbnail($model->photo, 800, 500) : "https://placeholdit.imgix.net/~text?txtsize=72&txt=800%C3%97500&w=800&h=500",
            ["class" => "img-responsive"])?>
        <div class="caption">
            <?=Html::tag("h3", $model->name)?>
            <?=Html::tag("p", mb_substr($model->description, 0, 128) . "...")?>
            <?=Html::a("Просмотр событий", Url::to(["/site/view-area", "id" => $model->id]), ["class" => "btn btn-primary"])?>
        </div>
    </div>
</div>

views/site/_item-event.php
<?php
/* @var $model app\models\Events */
use yii\helpers\Html;
use yii\helpers\Url;
use app\helpers\ImageHelper;
?>
<div class="col-md-4 list-item">
    <?=Html::img(
        !empty($model->show->image) ? ImageHelper::getThumbnail($model->show->image, 700, 400) : "https://placeholdit.imgix.net/~text?txtsize=72&txt=700%C3%97400&w=700&h=400",
        ["class" => "img-responsive"])?>
    <?=Html::tag("h3", $model->show->name)?>
    <?=Html::tag("span", $model->date, ["class" => "date"])?>
    <?=Html::a(Html::tag("h4", $model->area->name), Url::to(["/site/view-area", "id" => $model->area->id]))?>
    <?=Html::tag("p", mb_substr($model->show->description, 0, 255) . "...")?>
</div>

views/site/areas.php
<?php
use yii\widgets\ListView;
/* @var $this yii\web\View */

$this->title = 'Площадки';
?>
<div class="site-index">
    <?=
    ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_item-area',
        'itemOptions'   =>  [
            'tag'   => false
        ],
        'options' => [
        ],
        'layout' => "<div class='row text-center'>{items}</div>\n<div class='row text-center'><div class='col-xs-12'>{pager}</div></div>",
        'pager' => [
            'prevPageLabel' => '<span class="glyphicon glyphicon-chevron-left"></span>',
            'nextPageLabel' => '<span class="glyphicon glyphicon-chevron-right"></span>',
            'maxButtonCount' => 3,
        ],
    ])
    ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\widgets\ListView;
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">
    <?=
    ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_item-event',
        'options' => [
            'tag' => 'div',
            'class' => 'row',
            'id' => 'events-list',
        ],
        'layout' => "{items}\n<div class='row text-center'><div class='col-xs-12'>{pager}</div></div>",
        'pager' => [
            'prevPageLabel' => '<span class="glyphicon glyphicon-chevron-left"></span>',
            'nextPageLabel' => '<span class="glyphicon glyphicon-chevron-right"></span>',
            'maxButtonCount' => 3,
        ],
    ])
    ?>
</div>

views/site/view-area.php
<?php
/**
 * @var $model app\models\Areas
 */
use yii\helpers\Html;
use app\helpers\ImageHelper;
use yii\widgets\ListView;
?>
<div class="area-content">
    <div class="row">
        <div class="col-md-8">
            <?=Html::img(
                !empty($model->photo) ? ImageHelper::getThumbnail($model->photo, 900, 350) : "https://placeholdit.imgix.net/~text?txtsize=72&txt=900%C3%97350&w=900&h=350",
                ["class" => "img-responsive"])?>
        </div>
        <div class="col-md-4">
            <?=Html::tag("h1", $model->name)?>
            <?=Html::tag("p", $model->description)?>
        </div>
    </div>
    <div class="row">
        <?=
        ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_item-event',
            'options' => [
                'tag' => 'div',
                'class' => 'row',
                'id' => 'events-list',
            ],
            'layout' => "{items}\n<div class='row text-center'><div class='col-xs-12'>{pager}</div></div>",
            'pager' => [
                'prevPageLabel' => '<span class="glyphicon glyphicon-chevron-left"></span>',
                'nextPageLabel' => '<span class="glyphicon glyphicon-chevron-right"></span>',
                'maxButtonCount' => 3,
            ],
        ])
        ?>
    </div>
</div>